### ISSUE TITLE
Specific post(s) break the client

### ISSUE THREAD

**Issue by 0xAnansi** [asimons04/tesseract#4]
**What version of Tesseract has this bug?**
1.4.11

**Describe the bug**
Accessing a specific post in my instance breaks the whole client on Firefox and Chrome.

I couldn't isolate the issue, and can only reproduce with a single post, albeit a quite normal post.

**To Reproduce**
1. Go to the post about our lemmy update [on dubvee instance](https://tesseract.dubvee.org/post/jlai.lu/9488446) or on the [original instance](https://p.jlai.lu/post/jlai.lu/9488446)
2. Observe the loading not finishing
3. You'll need to refresh the client for it to be able to work again

**Expected behavior**
The page loads and displays the comments

**Screenshots**
![image](https://github.com/user-attachments/assets/ff08ba31-21d0-4292-a2b2-a7d53cb36f1e)

**What was tried**
- Loading posts with a similar number of comments (no bug)
- Loading other pinned post (no bug)
- Anonymous and logged in (no difference)

**Desktop (please complete the following information):**
 - OS: Garuda Linux (seem to be non OS dependant from user reports)
 - Browser: Chrome, Firefox
 - Version: latest for everything

**Additional context**
Docker options:
`docker run -d --name lemmy_tesseract --restart on-failure:10 -p 8080:3000 -e PUBLIC_INSTANCE_URL=jlai.lu -e PUBLIC_REMOVE_CREDIT=true -e PUBLIC_DEFAULT_COMMENT_SORT=Top -e PUBLIC_DEFAULT_FEED_SORT=Scaled -e PUBLIC_SSR_ENABLED=true -e PUBLIC_FAVICON=/img/logo-background.svg -e PUBLIC_LOCK_TO_INSTANCE=true ghcr.io/asimons04/tesseract:latest`

**Comment by asimons04** [comment]
Thanks for including the link to the post that triggered that.  Made it super easy to figure out what the issue was.

Problem was a bad match on a potential community link and not handling that cleanly.

Found and fixed in 1.4.12 (not released yet, but doing final testing and hopefully will be within the next 1-2 days).

Same post in 1.4.12:  https://dev.dubvee.org/post/jlai.lu/9488446

**Comment by asimons04** [comment]
If you want, I can build a "preview" release for 1.4.12 and you can run that if you need the fix sooner.

**Comment by 0xAnansi** [comment]
That was fast !

Don't worry about the preview, I've fixed the "domainless" link and it now works as intended. It'll be good enough until the release of the next version!

**Comment by asimons04** [comment]
I backported the fix to 1.4.11 and re-published the Docker images. You should be able to do a pull on the v1.4.11 tag to get the re-release.

**Comment by asimons04** [comment]
Backported fix to 1.4.11.  1.4.12 released which contains the fix.  Closing issue.
